CP/Models/NewSubscriptionViewModel.cs
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CP.Models
{
    public class NewSubscriptionViewModel
    {
        public NewSubscriptionViewModel()
        {
            Address = new Address();
            CommentRemark = new CommentRemark();
            Document = new Document();
            Person = new Person();
            Profile = new Profile();
            Request = new Request();
            //Appointment = new Appointment();
            User = new List<User>();
            Sources = new List<Source>();
            City = new List<City>();
            State = new List<State>();
        }

        //public List<RedemptionHistory> RedemptionHistory { get; set; }
        public Address Address { get; set; }
        public CommentRemark CommentRemark { get; set; }
        public Document Document { get; set; }
        public Person Person { get; set; }
        public Profile Profile { get; set; }
        public Request Request { get; set; }
        //public Appointment Appointment { get; set; }
        public List<User> User { get; set; }
        public List<StatusOfCase> StatusOfCases { get; set; }
        public List<Source> Sources { get; set; }
        public List<Packages> Packages { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public UserPosition UserPosition { get; set; }
        public List<UserAccess> CurrentUser { get; internal set; }
        public List<User> Users { get; internal set; }
        public List<State> State { get; set; }
        public List<City> City { get; set; }
    }
}

CP/Controllers/SubscriptionsController.cs
using DatabaseHelper.Store;
using IdentityManagement.Utilities;
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CP.Controllers
{
    public class SubscriptionsController : Controller
    {
        SubscriptionStore SubscriptionStore;
        UserAccessStore UserAccessStore;
        UserStore UserStore;
        RequestStore RequestStore;
        UserPositionStore UserPositionStore;
        StatusOfCaseStore StatusOfCaseStore;
        StateCityStore StateCityStore;
        PersonStore PersonStore;
        AddressStore AddressStore;
        ProfileStore ProfileStore;
        AuditTrailStore AuditTrailStore;
        PackageStore PackageStore;
        CommentRemarkStore CommentRemarkStore;
        DocumentStore DocumentStore;
        DraftStore DraftStore;
        SourceStore SourceStore;

        // GET: Case
        public ActionResult Index()
        {
            return View();
        }

        public SubscriptionsController()
        {
            SubscriptionStore = DependencyResolver.Current.GetService<SubscriptionStore>();
            UserAccessStore = DependencyResolver.Current.GetService<UserAccessStore>();
            UserStore = DependencyResolver.Current.GetService<UserStore>();
            RequestStore = DependencyResolver.Current.GetService<RequestStore>();
            UserPositionStore = DependencyResolver.Current.GetService<UserPositionStore>();
            StatusOfCaseStore = DependencyResolver.Current.GetService<StatusOfCaseStore>();
            StateCityStore = DependencyResolver.Current.GetService<StateCityStore>();
            PersonStore = DependencyResolver.Current.GetService<PersonStore>();
            AddressStore = DependencyResolver.Current.GetService<AddressStore>();
            ProfileStore = DependencyResolver.Current.GetService<ProfileStore>();
            AuditTrailStore = DependencyResolver.Current.GetService<AuditTrailStore>();
            PackageStore = DependencyResolver.Current.GetService<PackageStore>();
            CommentRemarkStore = DependencyResolver.Current.GetService<CommentRemarkStore>();
            DocumentStore = DependencyResolver.Current.GetService<DocumentStore>();
            DraftStore = DependencyResolver.Current.GetService<DraftStore>();
            SourceStore = DependencyResolver.Current.GetService<SourceStore>();
        }

        public async Task<ActionResult> Choice()
        {
            if (Utils.IfUserAuthenticated())
            {
                //var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var pid = "";

            if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                pid = Utils.GetProfileId();
            }

            var vm = new Models.SubscriptionIndexViewModal();
            //vm.Subscriptions = await SubscriptionStore.GetSubscriptions();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.User = await UserStore.GetUserByUserid(id);
            return View(vm);
        }

        public async Task<ActionResult> Subscription(string ProfileId, string page)
        {
            var p = Utils.GetUserGroup();
            var vm = new Models.SubscriptionIndexViewModal();
            vm.Subscription = await SubscriptionStore.GetSubscriptionByProfileId(ProfileId);
            vm.Profile = await ProfileStore.GetProfileByProfileId(ProfileId);
            vm.ProfileId = ProfileId;
            vm.Page = page;
            //vm.Address = await AddressStore.GetAddressByProfileId(ProfileId);
            //vm.Person = await PersonStore.GetPersonByProfileId(ProfileId);
            //vm.CommentRemark = await CommentRemarkStore.GetCommentRemarkByProfileId(ProfileId);
            //vm.ProfileAuditTrails = await AuditTrailStore.GetProfileAuditTrailByProfileId(ProfileId);
            //vm.Positions = await UserPositionStore.GetAllUserPosition();
            //vm.Users = await UserStore.GetAllUser();
            //vm.Sources = await SourceStore.GetAllSource();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            //vm.CommentRemark.RemoveAll(x => x.Type.TrimEnd() != "Profile");
            //vm.State = await StateCityStore.StateList();
            //vm.City = await StateCityStore.CityList();
            //vm.Page = page;
            return View(vm);
        }

        public async Task<ActionResult> _SubscriptionAccount(string profileId, string page)
        {
            if (Utils.IfUserAuthenticated())
            {
                //var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            //var pid = "";

            var vm = new Models.SubscriptionIndexViewModal();
            vm.Subscription = await SubscriptionStore.GetSubscriptionByProfileId(profileId);
            vm.Profile = await ProfileStore.GetProfileByProfileId(profileId);
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.SubscriptionAuditTrails = await AuditTrailStore.GetSubscriptionAuditTrailsByProfileId(profileId);
            vm.Page = page;

            return PartialView(vm);
        }

        public async Task<ActionResult> _RedemptionHistory(string profileId, string page)
        {
            if (Utils.IfUserAuthenticated())
            {
                //var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            //var pid = "";

            var vm = new Models.SubscriptionIndexViewModal();
            //vm.Subscription = await SubscriptionStore.GetSubscriptionByProfileId(profileId);
            //vm.Profile = await ProfileStore.GetProfileByProfileId(profileId);
            vm.RedemptionHistory = await SubscriptionStore.GetRedemptionHistories(profileId);
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.Page = page;

            return PartialView(vm);
        }

        public async Task<ActionResult> _Index()
        {
            if (Utils.IfUserAuthenticated())
            {
                //var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var pid = "";
            var status = 1;

            if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                pid = Utils.GetProfileId();
            }

            if (p == "22C63EE9-290E-4160-A293-6ECB49B4677F")
            {
                status = 2;
            }

            var vm = new Models.SubscriptionIndexViewModal();
            vm.SubscriptionRequest = await SubscriptionStore.GetSubscriptionRequests(status, id);
            vm.Packages = await PackageStore.GetPackages();
            vm.SubStatus = await SubscriptionStore.GetSubscriptionStatus();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.User = await UserStore.GetUserByUserid(id);

            return PartialView(vm);
        }

        public async Task<ActionResult> _PendingIndex()
        {
            if (Utils.IfUserAuthenticated())
            {
                //var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var pid = "";

            if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                pid = Utils.GetProfileId();
            }

            var vm = new Models.SubscriptionIndexViewModal();
            
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.User = await UserStore.GetUserByUserid(id);

            return PartialView(vm);
        }

        public async Task<ActionResult> NewSubscription()
        {
            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var userName = Utils.GetDisplayName();

            var vm = new Models.NewSubscriptionViewModel();
            vm.Request.CreatedBy = id;
            vm.Request.RequestId = await RequestStore.CreateRequest(vm.Request);
            vm.User = await UserStore.GetAllUser();
            vm.StatusOfCases = await StatusOfCaseStore.GetAllStatusOfCase();
            vm.UserPosition = await UserPositionStore.GetUserPositionByUserPositionId(p);
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.Packages = await PackageStore.GetPackages();
            vm.UserId = id;
            vm.State = await StateCityStore.StateList();
            vm.City = await StateCityStore.CityList();
            vm.Name = userName;
            vm.Users = await UserStore.GetAllUser();
            vm.Sources = await SourceStore.GetAllSource();




            if (TempData.ContainsKey("cr"))
            {
                vm.CommentRemark = TempData["cr"] as CommentRemark;
            }
            else
            {
                vm.CommentRemark = new CommentRemark();
            }

            if (TempData.ContainsKey("address"))
            {

CP/Views/Subscriptions/Choice.cshtml
@using CP.Models
@model SubscriptionIndexViewModal

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var rmo = Model.RMO;
    var page = "_Index";
    var user = Model.User;

}

<div class="bs-docs-section clearfix">
    <div class="col-lg-offset-1" style="margin-left:107px">

        <div class="col-lg-11 bg-white" style="margin-left:-15px;">
            <div class="bs-component" style="font-size:12px; margin-top: 20px; margin-bottom: 10px; margin-right:-1%">
                <ul class="nav nav-tabs cog-nav flex-display">

                            <li class="nav-item nav-link doc-nav active" style="width:170px; text-align:center"><a @*href="@Url.Action("Index", "Dashboard")"*@ id="subs" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-equalizer"></span> <br /><span style="font-size:10px; font-weight:bold">SUBSCRIPTION</span></a></li>

                            <li class="nav-item nav-link doc-nav" style="width:170px; text-align:center"><a @*href="@Url.Action("Index", "Dashboard")"*@ id="pending" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-equalizer"></span> <br /><span style="font-size:10px; font-weight:bold">PENDING SUBSCRIPTIONS</span></a></li>

                </ul>
            </div>
        </div><br /><br /><br /><br /><br /><br />
        <!-- jQuery and Bootstrap's JavaScript-->
        <div id="contentDiv">

        </div>

    </div>
</div>
<script>
     $(document).ready(function () {
        var url = '@Url.Action(page, "Subscriptions")';
        $("#contentDiv").load(url);
     });

    $(function () {
        $('#subs').click(function () {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_Index", "Subscriptions")';
            $("#contentDiv").load(url);
        });
        $('#pending').click(function() {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_PendingIndex", "Subscriptions")';
            $("#contentDiv").load(url);
        });
    });
</script>

CP/Views/Subscriptions/Subscription.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Subscription Preview";
}

@using CP.Models
@model SubscriptionIndexViewModal

@{
    //var disabled = "disabled";
    //var userId = Model.UserId;
    // var name = Model.Name;
    var cu = Model.CurrentUser;
    var page = "_SubscriptionAccount";
}

@*<script src="~/Scripts/Subscription.js"></script>

<script>
    $(function () {
        init();
    });
</script>*@

<style>
    .content .form-control {
        font-size: 11px;
    }

    .form-control {
        height: 25px;
        padding: 0px 5px;
        font-size: 11px;
    }

    .btn-info {
        background-color: #5bc0de;
    }
</style>

<div class="bs-docs-section clearfix">
    <div class="col-lg-offset-1" style="margin-left:107px">

        <div class="col-lg-11 bg-white" style="margin-left:-15px;">
            <div class="bs-component" style="font-size:12px; margin-top: 20px; margin-bottom: 10px; margin-right:-1%">
                <ul class="nav nav-tabs cog-nav flex-display">
                    <li class="nav-item nav-link doc-nav active" style="width:170px; text-align:center"><a @*href="@Url.Action("Index", "Dashboard")"*@ id="account" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-user"></span> <br /><span style="font-size:10px; font-weight:bold">ACCOUNT</span></a></li>
                    <li class="nav-item nav-link doc-nav" style="width:170px; text-align:center"><a @*href="@Url.Action("Index", "Dashboard")"*@ id="transaction" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-list-alt"></span> <br /><span style="font-size:10px; font-weight:bold">TRANSACTION HISTORY</span></a></li>
                </ul>
            </div>
        </div><br /><br /><br /><br /><br /><br />
        <!-- jQuery and Bootstrap's JavaScript-->
        <div id="contentDiv">

        </div>

    </div>
</div>
<script>
     $(document).ready(function () {
        var url = '@Url.Action(page, "Subscriptions", new { profileId = Model.ProfileId, Page = Model.Page })';
        $("#contentDiv").load(url);
     });

    $(function () {
        $('#account').click(function () {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_SubscriptionAccount", "Subscriptions", new { profileId = Model.ProfileId, Page = Model.Page })';
            $('#account').parent().addClass('active');
            $('#transaction').parent().removeClass('active');
            $("#contentDiv").load(url);
        });
        $('#transaction').click(function () {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_RedemptionHistory", "Subscriptions", new { profileId = Model.ProfileId, Page = Model.Page })';
            $('#transaction').parent().addClass('active');
            $('#account').parent().removeClass('active');
            $("#contentDiv").load(url);
        });
    });
</script>

CP/Views/Subscriptions/_Index.cshtml
@{
    ViewBag.Title = "Subscriptions";
}
@using CP.Models
@model SubscriptionIndexViewModal

@{
    var cu = Model.CurrentUser;
    var u = Model.User;
}

<style>
    .blue-title {
        margin-bottom: 0px;
        color: #225fef;
    }

    .form-control {
        height: 25px;
        padding: 0px 5px;
        font-size: 11px;
    }

    .btn-default {
        color: #333;
        background-color: #fff;
        border-color: #ccc;
    }

        .btn-default:focus,
        .btn-default.focus {
            color: #333;
            background-color: #e6e6e6;
            border-color: #8c8c8c;
        }

        .btn-default:hover {
            color: #333;
            background-color: #e6e6e6;
            border-color: #adadad;
        }
</style>

@{
    var canaccess = cu.Find(x => x.Keyword == "Subscription");
    if (canaccess != null && canaccess.IsRead)
    {
        <div class="row body-container" style="margin-top:-10px;">
            <div class="bs-component" style="font-size:11px; margin-top: 10px;">
                <div class="row col-lg-offset-1" style="margin-top:10px; margin-left:17px; width:88%">
                    <div style="margin-top:-35px;">
                        @if (canaccess.IsCreate)
                        {
                            @*<a id="createBtn" href="~/Subscriptions/NewSubscription" class="btn btn-danger btn-xs" style="float:right;">New Subscription</a>*@
                        }
                    </div>
                    @if (Model.SubscriptionRequest != null)
                    {
                        <table id="tblSubscriptionList" class="table sub-sub-table table-bordered" style="margin-bottom:20px; width:100%">
                            <thead>
                                <tr class="cpBG fontWhite">
                                    <th colspan="5">Subscription Information</th>
                                    <th colspan="4">Creditor Information</th>
                                </tr>

                                <tr style="font-weight:bold;">
                                    <td></td>
                                    <td style="vertical-align:middle">
                                        Reference No
                                    </td>
                                    <td style="vertical-align:middle">
                                        Subscription Plan
                                    </td>
                                    <td style="vertical-align:middle">
                                        Status
                                    </td>
                                    <td class="center-text" style="vertical-align:middle">
                                        Create Date
                                    </td>
                                    <td class="center-text" style="vertical-align:middle">
                                        Name
                                    </td>
                                    <td class="center-text" style="vertical-align:middle">
                                        Business Reg No
                                    </td>
                                    <td class="center-text" style="vertical-align:middle">
                                        Action
                                    </td>
                                </tr>

                                <tr class="search">
                                    <td style="vertical-align:middle" class="center-text" width="1%">
                                        <input type="checkbox" style="margin:0px" />
                                    </td>
                                    <td class="input-filter">
                                        <input type="text" class="form-control" placeholder="Reference No" />
                                    </td>
                                    <td class="input-filter">
                                        <select class="form-control" id="packageSelect">
                                            <option value="All">ALL</option>
                                            @foreach (var r in Model.Packages)
                                            {
                                                <option value="@r.PackageName">@r.PackageName.Trim()</option>
                                            }
                                        </select>
                                        <input type="hidden" id="status" class="form-control" placeholder="Status" />
                                    </td>
                                    <td class="input-filter">
                                        <select class="form-control" id="statusSelect">
                                            <option value="All">ALL</option>
                                            @foreach (var r in Model.SubStatus)
                                            {
                                                <option value="@r.Name">@r.Name.Trim()</option>
                                            }
                                        </select>
                                    </td>
                                    <td class="input-filter">
                                        <input type="text" class="form-control datepicker" placeholder="Subscribe Date" />
                                    </td>
                                    <td class="input-filter">
                                        <input type="text" class="form-control datepicker" placeholder="Active Date" />
                                    </td>
                                    <td class="input-filter">
                                        <input type="text" class="form-control datepicker" placeholder="Expire Date" />
                                    </td>
                                    <td class="center-text" width="5%">
                                        <button class="btn btn-xs btn-warning" id="btnClear">Clear</button>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                
                                @foreach (var r in Model.SubscriptionRequest)
                                {

                                    string refrence = "S" + r.RequestDate.ToString("yyyyMM");

                                    refrence = refrence + r.RequestId.Substring(0,4);


                                <tr>
                                    <td style="vertical-align:middle" class="center-text">
                                        <input type="checkbox" style="margin:0px" />
                                    </td>
                                    <td style="vertical-align:middle">
                                        <div class="ellipsis">
                                            <span>
                                                <a id="name" href="~/Subscriptions/SubscriptionApproval2?requestId=@r.RequestId">@refrence</a>
                                            </span>
                                        </div>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <span>
                                            @r.PackageName
                                        </span>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <span>
                                            @r.sName.Trim()
                                        </span>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <span>@r.RequestDate.ToString("dd MMM yyyy HH:mm:ss")</span>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <span>
                                            @r.Name
                                        </span>
                                    </td>
                                    <td style="vertical-align:middle">
                                        <span>
                                            @r.BusinessRegNo
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        @if (canaccess.IsUpdate)
                                        {
                                            <a href="#" class="btn btn-xs edit" title="Edit" style="padding:1px 1px;"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                        }

                                        @if (canaccess.IsDelete)
                                        {
                                            <a data-value="#" class="btn btn-xs delete" title="Delete" onclick="deleteLead(this)" style="padding:1px 1px;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                                        }
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    }

                    @{ 
                        if(u.Position == "22C63EE9-290E-4160-A293-6ECB49B4677F")
                        {

                        } else
                        {

                        }
                    }

                </div>
            </div>
        </div>
    }
    else
    {
        <h4 class="access-denied-page" style="color:black">
            Access denied, you don&acute;t have permission to access this page.
        </h4>
    }
}
<script>
    $(function () {
        $('.datepicker').datepicker({
            format: 'dd M yyyy'
        })
    });

    $(document).ready(function () {

        $('#select').on('change', function () {
            $('#source').val(this.value);
            if (this.value == "All") {
                $('#source').val('');
            }
            $('#source').change();
        });

        $('#statusSelect').on('change', function () {
            $('#status').val(this.value);
            if (this.value == "All") {
                $('#status').val('');
            }
            $('#status').change();
        });

        $('#subs').parent().addClass('active');
        $('#pending').parent().removeClass('active');

        $.fn.dataTable.moment('DD MMM YYYY HH:mm:ss');
        // DataTable
        var table = $('#tblSubscriptionList').DataTable({
            "pageLength": 25,
            "order": [[5, "desc"]],
            "dom": '<<"floatRight"p><t>>',
            "bSortCellsTop": true,
            "paging": true,
            "columnDefs": [
                { targets: 1, type: 'natural-nohtml' },
                { "orderable": false, "targets": 0 }
            ],
            "initComplete": function (settings, json) {
                //var a = $('#tblLeadList_paginate').parent().html();
                //$(a).insertAfter($('#createBtn'));
                $('#tblSubscriptionList_paginate').css({
                    'margin-right': '5px', 'padding': '1px'
                });
            }
        });

        $.each($('.input-filter', table.table().header()), function () {
            var column = table.column($(this).index());

            $('input', this).on('keyup change', function () {
                if (column.search() !== this.value) {
                    column
                        .search(this.value)
                        .draw();
                }
            });
        });

        $('#btnClear').click(function () {
            $.each($('.input-filter', table.table().header()), function () {
                table.search('').draw();
                $('input', this).val('');
                $('input', this).change();
            });
        });

    });
</script>