CP/Controllers/LayoutController.cs
using CP.Models;
using IdentityManagement.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CP.Controllers
{
    public class LayoutController : Controller
    {
        // GET: Layout
        public ActionResult _HeaderIcons()
        {
            var vm = new HeaderIconViewModel();

            if (Utils.IfUserAuthenticated())
            {
                vm.Name = Utils.GetUsername();
                vm.Position = Utils.GetUserGroup();
            }

            return PartialView(vm);
        }
    }
}

CP/Views/Shared/_ConfigLayout.cshtml
@using CP.Models
@model ConfigViewModel

@{
    Layout = "../Shared/_Layout.cshtml";
    string Module = Model.Module;
    var sops = Model.Sops;
}

<link href="~/Content/setting.css" rel="stylesheet" type="text/css" />

<style>
    .fixed-width {
        width: 175px !important;
    }
    .btn-group-vertical {
        width: 100%;
    }
</style>

<script>
    $(function () {
        var module = "@Module";
        var first = "DocType";

        if (module != "") {
            first = module;
        }

        var url = '@Url.Action("LoadConfigurationPage", "Confirguration")';
        $('.btn-sidenav').click(function () {
            $("#right-panel").load(url + "?module=_" + this.id);
        });
        $("#right-panel").load(url + "?module=_" + first);
    });
</script>

<div class="bs-docs-section clearfix body-container" style="margin-top:10px;">
    <div class="left-panel fixed-width">
        <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
            <a id="DocType" class="text-left btn btn-sm btn-sidenav active btn-info">
                @*<span class="glyphicon glyphicon-hdd">&nbsp;</span>*@
                Doc Type
            </a>
            <a class="btn btn-info collapsed" style="text-align:left; font-size:13px;" data-toggle="collapse" href="#access" role="button" aria-expanded="false" aria-controls="collapseExample">
                Access
            </a>
            <div class="collapse" id="access" aria-expanded="false" style="height: 0px;">
                <a id="Group" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Group
                </a>
                <a id="User" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    ID
                </a>
            </div>
            @*<a class="btn btn-info collapsed" style="text-align:left; font-size:13px;" data-toggle="collapse" href="#sops" role="button" aria-expanded="false" aria-controls="collapseExample">
                SOP
            </a>
            <div class="collapse" id="sops" aria-expanded="false" style="height: 0px;">
                @foreach (var s in sops)
                {
                    <a id="@s.Name.TrimEnd().Replace(" ","")" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                        @s.Name
                    </a>
                }
            </div>*@
            <a class="btn btn-info collapsed" style="text-align:left; font-size:13px;" data-toggle="collapse" href="#packages_list" role="button" aria-expanded="false" aria-controls="collapseExample">
                Packages
            </a>
            <div class="collapse" id="packages_list" aria-expanded="false" style="height: 0px;">
                <a id="Packages" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package
                </a>
                <a id="PackageServicesType" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package Services
                </a>
                <a id="PackageServicesConditionType" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package Services Condition Type
                </a>
            </div>
            <a class="btn btn-info collapsed" style="text-align:left; font-size:13px;" data-toggle="collapse" href="#packages_list" role="button" aria-expanded="false" aria-controls="collapseExample">
                Packages
            </a>
            <div class="collapse" id="packages_list" aria-expanded="false" style="height: 0px;">
                <a id="Packages" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package
                </a>
                <a id="PackageServices" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package Services
                </a>
                <a id="PackageServicesConditionType" class="text-right btn btn-sm btn-sidenav btn-info collapsed-btn" style="text-align:right;font-size:11px">
                    Package Services Condition Type
                </a>
            </div>
        </div>
    </div>
    <div class="right-panel" id="right-panel">
        @RenderBody()
    </div>
</div>

CP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@{ 
    string position = (string)Session["position"];
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.toast.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/site.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/datatables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/datetime-moment.js"></script>
    <script src="~/Scripts/natural.js"></script>

    <link href="~/Content/bootstrap-flat.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/login.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery.toast.css" rel="stylesheet" type="text/css" />
    <link href="~/Contents/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/datatables.min.css" rel="stylesheet" type="text/css" />
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

    <script>
        $(function () {
            $('.datepicker').datepicker({
                format: 'dd M yyyy'
            })
            $('[data-toggle="tooltip"]').tooltip({ placement: 'bottom' });
            initMain();
        });
    </script>
</head>
<body style="overflow-x:hidden; background-color:white; font-size:11px;">

    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                    <nav class="navbar navbar-default top-bar">
                        <div class="container-fluid cpBG" style="border-bottom:1px solid; border-bottom-color:#f9cc8b">
                            <div class="navbar-header top-logo" style=" padding-left:6.5%">
                                <a href="@Url.Action("Index", "Home", new { area = "" })" style="text-decoration:none;">
                                    <img src="~/Image/LogoGold.png" width="200"/>
                                </a>
                            </div>
                            @{ Html.RenderAction("_HeaderIcons", "Layout"); }
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div><br /><br /><br /><br />

    @RenderBody()
    <div class="modal fade" id="updatePassword" role="dialog" style="margin-top:2%">
        <div class="modal-dialog" style=" width: 25%;">
            <!-- Modal content-->
            <div class="modal-content" style="top: 20px;">
                <div class="modal-header" style="padding:8px 15px;">

                    <h4 class="modal-title">Change Password</h4>

                </div>
                <div class="modal-body" style="padding:0px 15px;">
                    <div class="modal-form">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>
                                        <p class="caption" style="font-style: italic;color: red;font-size: smaller;">Password must be minimal 8 characters, contain at least one digit, one special character and one capital alphabet.</p>
                                    </td>
                                </tr>

                                <tr>
                                    <td style="font-style:italic; padding:0px;">Current Password:</td>
                                </tr>
                                <tr>
                                    <td style="padding-top: 2px;padding-left: 0px;">
                                        <input type="password" id="inptCurPass" class="form-control" />
                                    </td>
                                </tr>

                                <tr>
                                    <td style="font-style:italic; padding:0px;">New Password:</td>
                                </tr>
                                <tr>
                                    <td style="padding-top: 2px;padding-left: 0px;">
                                        <input type="password" id="inptPass" class="form-control" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="font-style:italic; padding:0px;">
                                        Confirm Password:
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding-top: 2px;padding-left: 0px;">
                                        <input type="password" id="inptPass1" class="form-control" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer" style="padding:8px 15px;">
                    <button type="button" class="btn btn-xs btn-info" id="btnUpdate" disabled>Save</button>
                </div>
            </div>
        </div>
    </div>

    @*<div style="text-align:center; margin-bottom:30px;">
        © 2019 - <a href="@Url.Action("Index","Home")">Corporate Partners Debt Recovery Sdn Bhd</a>
    </div>*@
</body>
</html>