CP/Models/GroupViewModel.cs
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CP.Models
{
    public class GroupViewModel
    {
        public UserPosition Group { get; set; }
        public List<UserAccess> UserAccess { get; set; }
        public List<Access> AccessTypes { get; set; }
        public List<UserAccess> CurrentUser { get; set; }
    }
}

CP/Models/PackageViewModel.cs
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CP.Models
{
    public class PackageViewModel
    {
        public List<UserAccess> CurrentUser { get; set; }
        public List<Access> AccessTypes { get; set; }
        public List<PackageServices> PackageServices { get; set; }
        public User User { get; set; }
        public Packages Package { get; set; }
        public PackageServices PackageService { get; set; }
        public PackageServiceConditions PackageServiceConditions { get; set; }
    }
}

CP/Models/UserViewModel.cs
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CP.Models
{
    public class UserViewModel
    {
        public List<UserAccess> CurrentUser { get; set; }
        public List<UserPosition> Groups { get; set; }
        public List<Access> AccessTypes { get; set; }
        public List<LawFirmProfile> LawFirmProfiles { get; set; }
        public User User { get; set; }
        public List<Positions> Positions { get; internal set; }
    }
}

CP/Controllers/ConfirgurationController.cs
using DatabaseHelper.Store;
using IdentityManagement.Utilities;
using ObjectClassesLibrary;
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CP.Controllers
{
    public class ConfirgurationController : Controller
    {
        DocumentTypeStore DocumentTypeStore;
        ShowInSelectStore ShowInSelectStore;
        UserStore UserStore;
        UserPositionStore UserPositionStore;
        UserAccessStore UserAccessStore;
        AccessStore AccessStore;
        lawFirmLawFirmProfileStore lawFirmLawFirmProfileStore;
        SopStore SopStore;
        PositionsStore PositionsStore;
        PackageStore PackageStore;

        public ConfirgurationController()
        {
            DocumentTypeStore = DependencyResolver.Current.GetService<DocumentTypeStore>();
            ShowInSelectStore = DependencyResolver.Current.GetService<ShowInSelectStore>();
            UserStore = DependencyResolver.Current.GetService<UserStore>();
            UserPositionStore = DependencyResolver.Current.GetService<UserPositionStore>();
            UserAccessStore = DependencyResolver.Current.GetService<UserAccessStore>();
            AccessStore = DependencyResolver.Current.GetService<AccessStore>();
            lawFirmLawFirmProfileStore = DependencyResolver.Current.GetService<lawFirmLawFirmProfileStore>();
            SopStore = DependencyResolver.Current.GetService<SopStore>();
            PositionsStore = DependencyResolver.Current.GetService<PositionsStore>();
            PackageStore = DependencyResolver.Current.GetService<PackageStore>();
        }
        // GET: Confirguration
        public async Task<ActionResult> Index(string module)
        {
            if (Utils.IfUserAuthenticated())
            {
                var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var vm = new Models.ConfigViewModel();
            vm.Module = module;
            vm.Sops = await SopStore.SopList();
            if (!string.IsNullOrEmpty(module))
            {
                module = null;
            }

            return View(vm);
        }
        public async Task<ActionResult> LoadConfigurationPage(string module)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.ConfigViewModel();
            vm.Users = await UserStore.GetAllUser();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);

            switch (module)
            {
                case "_DocType":
                    vm.DocumentType = await DocumentTypeStore.GetAllDocumentType();
                    vm.ShowInSelects = await ShowInSelectStore.GetAllShowInSelect();
                    vm.DocumentType.RemoveAll(x => x.Deleted == true);
                    vm.ShowInSelects.RemoveAll(x => x.Deleted == true);
                    break;
                case "_User":
                    vm.Users = vm.Users.OrderBy(x => x.Name).ToList();
                    vm.UserPositions = await UserPositionStore.GetAllUserPosition();
                    vm.UserPositions.RemoveAll(x => x.Deleted == true);
                    vm.Positions = await PositionsStore.GetPositions();
                    break;
                case "_Group":
                    vm.UserPositions = await UserPositionStore.GetAllUserPosition();
                    vm.UserPositions.RemoveAll(x => x.Deleted == true);
                    break;
                case "_Packages":
                    vm.Packages = await PackageStore.GetPackages();
                    break;
                case "_PackageServices":
                    vm.PackageServices = await PackageStore.GetPackageServices();
                    vm.ConditionTypes = await PackageStore.GetConditionTypes();
                    break;
                case "_PackageServicesConditionType":
                    vm.ConditionTypes = await PackageStore.GetConditionTypes();
                    break;
            }


            return PartialView(module, vm);
        }
        public async Task<ActionResult> CreateGroup()
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.GroupViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.AccessTypes = await AccessStore.AccessList();
            vm.UserAccess = await UserAccessStore.GetAllUserAccess();

            return View(vm);
        }
        public async Task<ActionResult> EditGroup(string groupId)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.GroupViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.Group = await UserPositionStore.GetUserPositionByUserPositionId(groupId);
            vm.UserAccess = await UserAccessStore.GetUserAccessByUserPositionId(groupId);
            vm.AccessTypes = await AccessStore.AccessList();

            return View(vm);
        }
        public async Task<ActionResult> EditGroupPreview(string groupId)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.GroupViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.Group = await UserPositionStore.GetUserPositionByUserPositionId(groupId);
            vm.UserAccess = await UserAccessStore.GetUserAccessByUserPositionId(groupId);
            vm.AccessTypes = await AccessStore.AccessList();

            return View(vm);
        }
        public async Task<ActionResult> AddNewPackage()
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.PackageViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            //vm.Groups = await UserPositionStore.GetAllUserPosition();
            vm.AccessTypes = await AccessStore.AccessList();
            //vm.Groups.RemoveAll(x => x.Deleted == true);
            //vm.LawFirmProfiles = await lawFirmLawFirmProfileStore.GetAllLawFirmProfile();
            //vm.Positions = await PositionsStore.GetPositions();

            return View(vm);
        }
        public async Task<ActionResult> EditPackage(string packageId)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.PackageViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.AccessTypes = await AccessStore.AccessList();
            vm.Package = await PackageStore.GetPackagesByPackageId(packageId);

            return View(vm);
        }

        public async Task<ActionResult> EditPackageService(string serviceId)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.ConfigViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.AccessTypes = await AccessStore.AccessList();
            vm.PackageService = await PackageStore.GetPackageServiceByServiceId(serviceId);
            vm.PackageServiceConditions = await PackageStore.GetPackageServiceConditionsByServiceId(serviceId);
            vm.ConditionTypes = await PackageStore.GetConditionTypes();

            return View(vm);
        }

        public async Task<JsonResult> updateConditionSelect(string serviceId)
        {
            var vm = new Models.ConfigViewModel();
            vm.PackageServiceConditions = await PackageStore.GetPackageServiceConditionsByServiceId(serviceId);
            vm.PackageService = await PackageStore.GetPackageServiceByServiceId(serviceId);
            return Json(vm);
        }


        public async Task<ActionResult> AddNewPackageService()
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.ConfigViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            //vm.Groups = await UserPositionStore.GetAllUserPosition();
            vm.AccessTypes = await AccessStore.AccessList();
            //vm.Groups.RemoveAll(x => x.Deleted == true);
            //vm.LawFirmProfiles = await lawFirmLawFirmProfileStore.GetAllLawFirmProfile();
            //vm.Positions = await PositionsStore.GetPositions();
            vm.ConditionTypes = await PackageStore.GetConditionTypes();
            return View(vm);
        }
        public async Task<JsonResult> CreateNewConditionType(string condName)
        {
            string id = Utils.GetUserId();
            var r = new Response();
            var a = await PackageStore.CreateNewConditionType(condName, id);


                r.Message = "Condition type added successfully.";

                r.RedirectUrl = "/Confirguration?module=PackageServicesConditionType";
            return Json(r);
        }
        public async Task<ActionResult> CreateUser()
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.UserViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);
            vm.Groups = await UserPositionStore.GetAllUserPosition();
            vm.AccessTypes = await AccessStore.AccessList();
            vm.Groups.RemoveAll(x => x.Deleted == true);
            vm.LawFirmProfiles = await lawFirmLawFirmProfileStore.GetAllLawFirmProfile();
            vm.Positions = await PositionsStore.GetPositions();

            return View(vm);
        }
        public async Task<ActionResult> EditUser(string userId)
        {
            string position = Utils.GetUserGroup();
            var vm = new Models.UserViewModel();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(position);

CP/Views/Confirguration/EditGroupPreview.cshtml
@using CP.Models
@model GroupViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var group = Model.Group;
    var accesses = Model.UserAccess;
    var currentUser = Model.CurrentUser;
    ViewBag.Title = "Group Preview";
}


<script src="~/Scripts/group.js"></script>
<script>
    $(function () {
        init();
    });
</script>

<style>
    .content .form-control {
        font-size: 11px;
    }

    .form-control {
        height: 25px;
        padding: 0px 5px;
        font-size: 11px;
    }
</style>

<input type="hidden" id="groupId" value="@group.UserPositionId" />

<div class="col-lg-offset-1 col-lg-10">
    <div>
        <h3 class="h3-page-header">Group Preview</h3>
    </div>
    <div class="col-lg-12 bg-white" style="padding:0px">
        <div class="bs-component" style="font-size:11px;">
            @{
                var caccess = currentUser.Find(x => x.Keyword == "Configuration");
                if (caccess != null && caccess.IsRead)
                {
                    <table id="tblGroup" class="table table-col-4 table-bordered">
                        <tbody>
                            <tr class="cpBG fontWhite">
                                <td colspan="4">GROUP INFORMATION</td>
                            </tr>
                            <tr style="color:black">
                                <td style="vertical-align:middle" width="16%">
                                    <label style="color:black" class="font-weight-bold">Group Name</label>
                                </td>
                                <td width="28%">
                                    @group.Name
                                </td>
                                <td style="vertical-align:middle" width="28%">
                                    <label style="color:black" class="font-weight-bold">Remark / Description</label>
                                </td>
                                <td width="28%">
                                    @group.Description
                                </td>
                            </tr>

                            <tr class="cpBG fontWhite">
                                <td colspan="5">GROUP ACCESS</td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                    <table id="tblGroupAccess" class="table table-bordered sub-table">
                                        <thead>
                                            <tr style="color:black">
                                                <th rowspan="2" width="10%">Module</th>
                                                <th colspan="5">Access</th>
                                            </tr>
                                            <tr style="color:black">
                                                <th>View Only<p style="color:red" class="sub-th">view only access</p></th>
                                                <th>Create Only<p style="color:red" class="sub-th">create only access </p></th>
                                                <th>Update Only<p style="color:red" class="sub-th">update only access</p></th>
                                                <th>Delete Only<p style="color:red" class="sub-th">delete only access</p></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                                foreach (var a in Model.AccessTypes)
                                                {
                                                    var access = accesses.Find(x => x.AccessId == a.AccessId);
                                                    <tr>
                                                        <td data-access="@a.AccessId" style="color:black" width="15.55%">
                                                            @a.Name
                                                        </td>
                                                        <td width="21%">
                                                            @{
                                                                if (access != null && access.IsRead)
                                                                {
                                                                    <input type="checkbox" name="readonly" disabled checked @*onchange="validateCheck(this)"*@ />
                                                                }
                                                                else
                                                                {
                                                                    <input type="checkbox" name="readonly" disabled @*onchange="validateCheck(this)"*@ />
                                                                }
                                                            }
                                                        </td>
                                                        <td width="21%">
                                                            @{
                                                                if (access != null && access.IsCreate)
                                                                {
                                                                    <input type="checkbox" name="create" disabled checked @*onchange="validateCheck(this)"*@ />
                                                                }
                                                                else
                                                                {
                                                                    <input type="checkbox" name="create" disabled @*onchange="validateCheck(this)"*@ />
                                                                }
                                                            }

                                                        </td>
                                                        <td width="21%">
                                                            @{
                                                                if (access != null && access.IsUpdate)
                                                                {
                                                                    <input type="checkbox" name="update" disabled checked @*onchange="validateCheck(this)"*@ />
                                                                }
                                                                else
                                                                {
                                                                    <input type="checkbox" name="update" disabled @*onchange="validateCheck(this)"*@ />
                                                                }
                                                            }
                                                        </td>
                                                        <td width="21%">
                                                            @{
                                                                if (access != null && access.IsDelete)
                                                                {
                                                                    <input type="checkbox" name="delete" disabled checked @*onchange="validateCheck(this)"*@ />
                                                                }
                                                                else
                                                                {
                                                                    <input type="checkbox" name="delete" disabled @*onchange="validateCheck(this)"*@ />
                                                                }
                                                            }
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div style="text-align:right; margin-top:5px;">
                        @if (caccess.IsUpdate)
                        {
                            <a href="@Url.Action("EditGroup", "Confirguration", new { groupId = group.UserPositionId })" class="btn btn-xs btn-danger">Edit</a>
                        }
                        <a href="~/Confirguration/Index?module=Group" class="btn btn-xs btn-default">Close</a>
                    </div>
                }
                else
                {
                    <h4 class="access-denied-page" style="color:black">
                        Access denied, you don&acute;t have permission to access this page.
                    </h4>
                }
            }
        </div>
    </div>
</div>

CP/Views/Confirguration/EditPackagePreview.cshtml
@using CP.Models
@model PackageViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var cu = Model.CurrentUser;
    var pd = Model.PackageServicesType;
    var sops = Model.Sops;
    var package = Model.Package;
    var pss = Model.PackageService_Sops;
    ViewBag.Title = "Edit Package Preview";
    var c = "checked";
}

<style>
    .content .form-control {
        font-size: 11px;
    }

    .form-control {
        height: 25px;
        padding: 0px 5px;
        font-size: 11px;
    }

    .grayout {
        opacity: 0.6; /* Real browsers */
        filter: alpha(opacity = 60); /* MSIE */
        cursor: not-allowed;
    }
</style>

<div class="col-lg-offset-1 col-lg-10">
    <div>
        <h3 class="h3-page-header">Edit Package Preview</h3>
    </div>
    <div class="col-lg-12 bg-white" style="padding:0">
        <div class="bs-component" style="font-size:11px;">
            @{
                var caccess = cu.Find(x => x.Keyword == "Configuration");
                if (caccess != null && caccess.IsRead)
                {
                    <table id="tblPackage" class="table table-column-8 table-bordered">
                        <tbody>
                            <tr class="cpBG fontWhite">
                                <td colspan="8">PACKAGE INFORMATION</td>
                            </tr>
                            <tr>
                                <td style="vertical-align:middle">
                                    <label class="font-weight-bold" style="color:black">Package Name</label>
                                </td>
                                <td style="vertical-align:middle; width:30%" class="blackFont">
                                    @package.PackageName
                                </td>
                                <td style="vertical-align:middle">
                                    <label class="font-weight-bold" style="color:black">Price (RM)</label>
                                </td>
                                <td style="vertical-align:middle; width:8%" class="blackFont">
                                    @package.SubscriptionFee_RM.ToString("F")
                                </td>
                                <td style="vertical-align:middle">
                                    <label class="font-weight-bold" style="color:black">Service Credit(SC)</label>
                                </td>
                                <td class="blackFont">
                                    @package.CreditGiven.ToString("F")
                                </td>
                                <td style="vertical-align:middle;">
                                    <label class="font-weight-bold" style="color:black">Validity Period</label>
                                </td>
                                <td style="vertical-align:middle; width:8%" class="blackFont">
                                    @package.Validity_Months
                                </td>
                            </tr>
                            <tr style="color:black" class="thisRow">
                                <td>
                                    <label class="font-weight-bold" style="color:black">Status</label>
                                </td>
                                <td>
                                    <label>
                                        @{
                                            var status = "";
                                            var color = "";
                                        }
                                        @switch (package.Status)
                                        {
                                            case true:
                                                status = "Active";
                                                color = "green";
                                                break;
                                            case false:
                                                status = "Inactive";
                                                color = "red";
                                                break;
                                        }

                                        <label style="font-weight:bold; color:@color">@status</label>
                                    </label>

                                </td>

                                <td>
                                    <label class="font-weight-bold" style="color:black">Package Description</label>
                                </td>
                                <td colspan="5" class="blackFont">
                                    @package.PackageDesc
                                </td>
                            </tr>
                            <tr style="color:black" class="thisRow">
                                <td>
                                    <label class="font-weight-bold" style="color:black">SOP Services</label>
                                </td>
                                <td>
                                    <table class="table table-bordered sub-table thisTable" style="margin-bottom:0px">
                                        <tbody>
                                            @foreach (var s in sops)
                                            {
                                                <tr>
                                                    <td>
                                                        @{
                                                            var ps = pss.Find(x => x.SopId == s.SopId && x.Type == "Sop");

                                                            if (ps != null)
                                                            {
                                                                <input disabled type="checkbox" class="thisCb" name="packages_sop_type" @{ if (ps.Active) { @c  } } data-packageserviceid="@ps.PackageServiceId" data-type="Sop" value="@s.SopId" id="@s.SopId"> <label for="@s.SopId">@s.Name</label>
                                                            }
                                                            else
                                                            {
                                                                <input disabled type="checkbox" class="thisCb" name="packages_sop_type" data-type="Sop" value="@s.SopId" id="@s.SopId"> <label for="@s.SopId">@s.Name</label>
                                                            }
                                                        }
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                                <td>
                                    <label class="font-weight-bold" style="color:black">Manual Services</label>
                                </td>
                                <td colspan="5">
                                    <table class="table table-bordered sub-table thisTable" style="margin-bottom:0px">
                                        <tbody>
                                            @foreach (var s in pd)
                                            {
                                                <tr>
                                                    <td>
                                                        @{
                                                            var ps = pss.Find(x => x.ServiceTypeId == s.ServiceId && x.Type == "Service");

                                                            if (ps != null)
                                                            {
                                                                <input disabled type="checkbox" class="thisCb" name="packages_service_type" @{ if (ps.Active) { @c  } } data-packageserviceid="@ps.PackageServiceId" data-type="Service" value="@s.ServiceId" id="@s.ServiceId"> <label for="@s.ServiceId">@s.ServiceName</label>
                                                            }
                                                            else
                                                            {
                                                                <input disabled type="checkbox" class="thisCb" name="packages_service_type" data-type="Service" value="@s.ServiceId" id="@s.ServiceId"> <label for="@s.ServiceId">@s.ServiceName</label>
                                                            }
                                                        }
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div style="text-align:right; margin-top:5px;">
                        @if (caccess.IsUpdate)
                        {
                            <a href="@Url.Action("EditPackage", "Confirguration", new { packageId = package.PackageId })" class="btn btn-xs btn-danger">Edit</a>
                        }
                        <a href="~/Confirguration/Index?module=Packages" class="btn btn-xs btn-default">Close</a>
                    </div>
                }
                else
                {
                    <h4 class="access-denied-page" style="color:black">
                        Access denied, you don&acute;t have permission to access this page.
                    </h4>
                }
            }
        </div>
    </div>
</div>

CP/Views/Confirguration/Index.cshtml
@{
    Layout = "../Shared/_ConfigLayout.cshtml";
}

<div id="ConfigPage" class="panel-body background-white">
</div>