CP/Controllers/CloseController.cs
using DatabaseHelper.Store;
using IdentityManagement.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CP.Controllers
{
    public class CloseController : Controller
    {
        UserStore UserStore;
        RequestStore RequestStore;
        ProfileStore ProfileStore;
        LeadStore LeadStore;
        SourceStore SourceStore;
        StatusStore StatusStore;
        UserAccessStore UserAccessStore;

        public CloseController()
        {
            UserStore = DependencyResolver.Current.GetService<UserStore>();
            RequestStore = DependencyResolver.Current.GetService<RequestStore>();
            ProfileStore = DependencyResolver.Current.GetService<ProfileStore>();
            LeadStore = DependencyResolver.Current.GetService<LeadStore>();
            SourceStore = DependencyResolver.Current.GetService<SourceStore>();
            StatusStore = DependencyResolver.Current.GetService<StatusStore>();
            UserAccessStore = DependencyResolver.Current.GetService<UserAccessStore>();
        }
        // GET: Close
        public async Task<ActionResult> _Index()
        {
            if (Utils.IfUserAuthenticated())
            {
                var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var pid = "";

            if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                pid = Utils.GetProfileId();
            }

            var vm = new Models.LeadIndexViewModel();
            vm.Requests = await RequestStore.GetAllRequest();
            vm.Profiles = await ProfileStore.GetAllProfile();
            vm.Leads = await LeadStore.GetAllLead();
            vm.Users = await UserStore.GetAllUser();
            vm.Sources = await SourceStore.GetAllSource();
            vm.Statuses = await StatusStore.StatusList();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.UserId = id;

            vm.Requests.RemoveAll(x => x.ProfileId == null && x.AddressId == null && x.PersonId == null && x.CommentRemarkId == null);
            vm.Requests.RemoveAll(x => x.Status == null);
            vm.Requests = vm.Requests.FindAll(x => x.Stage == 21 || x.Stage == 35);
            if (p == "011C9D8F-A82A-4BE3-9F30-4C2CEDE0D487")
            {
                vm.Leads.RemoveAll(x => x.AssignTo != id);
                vm.Requests.RemoveAll(x => x.Stage < 1);
            }
            else if (p == "22C63EE9-290E-4160-A293-6ECB49B4677F")
            {
                vm.Requests.RemoveAll(x => x.Approval1User == null && x.Approval2User == null);
            }
            else if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                vm.Requests.RemoveAll(x => x.LawFirm != pid);
            }
            else if (p == "E207490E-1A8C-405D-B415-B100ADB0D04F")
            {
                vm.Requests.RemoveAll(x => x.NegotiatorId != id);
            }
            else if (p == "FD23EA98-5D5E-464C-B109-EE7F8E5211C5")
            {
                vm.Requests.RemoveAll(x => x.Stage < 33);
            }
            else if (p == "2788371D-8EC5-4ABE-A189-2A3B8562CAF1")
            {
                vm.Leads.RemoveAll(x => x.AssignTo == null);
                vm.Requests.RemoveAll(x => x.Stage < 1);
            }
            else if (p == "7D68595F-726A-4D9F-8BF2-42DA814901C5")
            {
                vm.Requests.RemoveAll(x => x.NegotiatorId == null);
            }
            else if (p == "A4C2EBBE-9391-44AF-BD49-572BBC9EB22E")
            {
                vm.Requests.RemoveAll(x => x.Stage == 1);
            }
            foreach (var v in vm.Requests)
            {
                v.AccessStatus = new ObjectClassesLibrary.Classes.LeadUserHasAccess().checkAccess(p, v.Stage, id);
            }

            return PartialView(vm);
        }
    }
}

CP/Controllers/LeadController.cs
using DatabaseHelper.Store;
using ObjectClassesLibrary.Classes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using WordToPDF;
using System.Text;
using ObjectClassesLibrary;
using IdentityManagement.Utilities;

namespace CP.Controllers
{
    public class LeadController : Controller
    {
        AddressStore AddressStore;
        CommentRemarkStore CommentRemarkStore;
        DocumentStore DocumentStore;
        DocumentTypeStore DocumentTypeStore;
        PersonStore PersonStore;
        ProfileStore ProfileStore;
        RequestStore RequestStore;
        LeadStore LeadStore;
        UserStore UserStore;
        AppointmentStore AppointmentStore;
        StatusOfCaseStore StatusOfCaseStore;
        AssetForInvestigationStore AssetForInvestigationStore;
        CompanyFinancialInformationStore CompanyFinancialInformationStore;
        LitigationRecordStore LitigationRecordStore;
        BlackListingRecordStore BlackListingRecordStore;
        SourceStore SourceStore;
        AuditTrailStore AuditTrailStore;
        UserPositionStore UserPositionStore;
        DebtorStore DebtorStore;
        AppointmentTypeStore AppointmentTypeStore;
        ShowInSelectStore ShowInSelectStore;
        lawFirmLawFirmProfileStore lawFirmLawFirmProfileStore;
        DraftStore DraftStore;
        StateCityStore StateCityStore;
        StatusStore StatusStore;
        UserAccessStore UserAccessStore;
        SopStore SopStore;
        SopRequestsStore SopRequestsStore;
        RequestServiceStore RequestServiceStore;
        PackageStore PackageStore;
        SubscriptionStore SubscriptionStore;

        public LeadController()
        {
            AddressStore = DependencyResolver.Current.GetService<AddressStore>();
            CommentRemarkStore = DependencyResolver.Current.GetService<CommentRemarkStore>();
            DocumentStore = DependencyResolver.Current.GetService<DocumentStore>();
            DocumentTypeStore = DependencyResolver.Current.GetService<DocumentTypeStore>();
            PersonStore = DependencyResolver.Current.GetService<PersonStore>();
            ProfileStore = DependencyResolver.Current.GetService<ProfileStore>();
            RequestStore = DependencyResolver.Current.GetService<RequestStore>();
            LeadStore = DependencyResolver.Current.GetService<LeadStore>();
            UserStore = DependencyResolver.Current.GetService<UserStore>();
            AppointmentStore = DependencyResolver.Current.GetService<AppointmentStore>();
            StatusOfCaseStore = DependencyResolver.Current.GetService<StatusOfCaseStore>();
            AssetForInvestigationStore = DependencyResolver.Current.GetService<AssetForInvestigationStore>();
            CompanyFinancialInformationStore = DependencyResolver.Current.GetService<CompanyFinancialInformationStore>();
            LitigationRecordStore = DependencyResolver.Current.GetService<LitigationRecordStore>();
            BlackListingRecordStore = DependencyResolver.Current.GetService<BlackListingRecordStore>();
            SourceStore = DependencyResolver.Current.GetService<SourceStore>();
            AuditTrailStore = DependencyResolver.Current.GetService<AuditTrailStore>();
            UserPositionStore = DependencyResolver.Current.GetService<UserPositionStore>();
            DebtorStore = DependencyResolver.Current.GetService<DebtorStore>();
            AppointmentTypeStore = DependencyResolver.Current.GetService<AppointmentTypeStore>();
            ShowInSelectStore = DependencyResolver.Current.GetService<ShowInSelectStore>();
            lawFirmLawFirmProfileStore = DependencyResolver.Current.GetService<lawFirmLawFirmProfileStore>();
            DraftStore = DependencyResolver.Current.GetService<DraftStore>();
            StateCityStore = DependencyResolver.Current.GetService<StateCityStore>();
            StatusStore = DependencyResolver.Current.GetService<StatusStore>();
            UserAccessStore = DependencyResolver.Current.GetService<UserAccessStore>();
            SopStore = DependencyResolver.Current.GetService<SopStore>();
            SopRequestsStore = DependencyResolver.Current.GetService<SopRequestsStore>();
            RequestServiceStore = DependencyResolver.Current.GetService<RequestServiceStore>();
            PackageStore = DependencyResolver.Current.GetService<PackageStore>();
            SubscriptionStore = DependencyResolver.Current.GetService<SubscriptionStore>();
        }

        public async Task<ActionResult> _Index()
        {
            if (Utils.IfUserAuthenticated())
            {
                var u = await UserStore.GetUserByUserid(Utils.GetUserId());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var pid = "";

            if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                pid = Utils.GetProfileId();
            }

            var vm = new Models.LeadIndexViewModel();
            vm.Requests = await RequestStore.GetAllRequest();
            vm.Profiles = await ProfileStore.GetAllProfile();
            vm.Leads = await LeadStore.GetAllLead();
            vm.Users = await UserStore.GetAllUser();
            vm.Sources = await SourceStore.GetAllSource();
            vm.Statuses = await StatusStore.StatusList();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.Drafts = await DraftStore.GetDraftByCreatedById(id);
            vm.AuditTrails = await AuditTrailStore.GetAllAuditTrail();
            vm.UserId = id;

            vm.Requests.RemoveAll(x => x.ProfileId == null && x.AddressId == null && x.PersonId == null && x.CommentRemarkId == null);
            vm.Requests.RemoveAll(x => x.Status == null);
            vm.Requests.RemoveAll(x => x.Status.Length >= 4 && x.Status.Substring(0, 4) == "Case");
            vm.Statuses.RemoveAll(x => x.Name.Length >= 4 && x.Name.Substring(0, 4) == "Case");
            if (p == "011C9D8F-A82A-4BE3-9F30-4C2CEDE0D487")
            {
                vm.Leads.RemoveAll(x => x.AssignTo != id);
                vm.Requests.RemoveAll(x => x.Stage < 1);
            }
            else if (p == "22C63EE9-290E-4160-A293-6ECB49B4677F")
            {
                vm.Requests.RemoveAll(x => x.Approval1User == null && x.Approval2User == null);
            }
            else if (p == "47461275-5753-47D1-8A8B-9A26D91E03A4")
            {
                vm.Requests.RemoveAll(x => x.LawFirm != pid);
            }
            else if (p == "E207490E-1A8C-405D-B415-B100ADB0D04F")
            {
                vm.Requests.RemoveAll(x => x.NegotiatorId != id);
            }
            else if (p == "FD23EA98-5D5E-464C-B109-EE7F8E5211C5")
            {
                vm.Requests.RemoveAll(x => x.Stage < 27);
            }
            else if (p == "2788371D-8EC5-4ABE-A189-2A3B8562CAF1")
            {
                vm.Leads.RemoveAll(x => x.AssignTo == null);
                vm.Requests.RemoveAll(x => x.Stage < 1);
            }
            else if (p == "7D68595F-726A-4D9F-8BF2-42DA814901C5")
            {
                vm.Requests.RemoveAll(x => x.NegotiatorId == null);
            }
            else if (p == "A4C2EBBE-9391-44AF-BD49-572BBC9EB22E")
            {
                vm.Requests.RemoveAll(x => x.Stage == 1);
            }

            foreach (var v in vm.Requests)
            {
                v.AccessStatus = new ObjectClassesLibrary.Classes.LeadUserHasAccess().checkAccess(p, v.Stage, id);
            }

            return PartialView(vm);
        }
        public async Task<ActionResult> CreateLead()
        {
            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            var userName = Utils.GetDisplayName();

            var vm = new Models.CreateLeadViewModel();
            //vm.Request.CreatedBy = id;
            //vm.Request.RequestId = await RequestStore.CreateRequest(vm.Request);
            vm.User = await UserStore.GetAllUser();
            vm.StatusOfCases = await StatusOfCaseStore.GetAllStatusOfCase();
            vm.Sources = await SourceStore.GetAllSource();
            vm.Sources.RemoveAll(x => x.Deleted == true);
            vm.UserPosition = await UserPositionStore.GetUserPositionByUserPositionId(p);
            vm.States = await StateCityStore.StateList();
            vm.Cities = await StateCityStore.CityList();
            vm.CurrentUser = await UserAccessStore.GetUserAccessByUserPositionId(p);
            vm.UserId = id;
            vm.Name = userName;
            vm.Users = await UserStore.GetAllUser();

            vm.User = vm.User.FindAll(x => x.Position == "011C9D8F-A82A-4BE3-9F30-4C2CEDE0D487");
            if (p == "011C9D8F-A82A-4BE3-9F30-4C2CEDE0D487")
            {
                vm.User.RemoveAll(x => x.UserId != id);
            }

            return View(vm);
        }
        public async Task<JsonResult> CreateNewLead(Profile profile, Address address, Person person, CommentRemark cr, Request request, Lead lead, AssetForInvestigation afi, IList<CompanyFinancialInformation> cfi, IList<LitigationRecord> lr, IList<BlackListingRecord> br, IList<ObjectClassesLibrary.Classes.Document> documents, AuditTrail auditTrail)
        {
            var p = Utils.GetUserGroup();
            var id = Utils.GetUserId();
            cr.CreatedBy = id;

            if (p == "011C9D8F-A82A-4BE3-9F30-4C2CEDE0D487")
            {
                lead.AssignTo = id;
            }

            string caseSwitch = lead.AssignTo;
            switch (caseSwitch)
            {
                case null:
                case "":
                    request.Stage = 0;
                    break;

CP/Views/Case/Choice.cshtml
@using CP.Models
@model LeadIndexViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var rmo = Model.RMO;
    var page = "_Index";

    if (Model.Module == "Case")
    {
        page = "_CaseIndex";
    }
}


<div class="bs-docs-section clearfix" style="margin-top:10px;">
    <div class="col-lg-offset-1" style="margin-left:107px">

        <div class="col-lg-11 bg-white" style="margin-left:-15px;">
            <div class="bs-component" style="font-size:12px; margin-top: 10px; margin-bottom: 10px; margin-right:-1%">
                <ul class="nav nav-tabs cog-nav flex-display">
                    <li class="nav-item nav-link doc-nav active" style="width:170px; text-align:center"><a @*href="@Url.Action("Choice","ChangeEquipment")"*@ id="lead" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-user"></span> <br /><span style="font-size:10px; font-weight:bold; margin-left:-5px;">LEAD</span></a></li>
                    <li class="nav-item nav-link doc-nav" style="width:170px; text-align:center"><a @*href="@Url.Action("Choice","Notification")"*@ id="appointment" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-list"></span> <br /><span style="font-size:10px; font-weight:bold">APPOINTMENT</span></a></li>
                    <li class="nav-item nav-link doc-nav" style="width:170px; text-align:center"><a @*href="@Url.Action("Choice","Notification")"*@ id="case" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-cog"></span> <br /><span style="font-size:10px; font-weight:bold; margin-left:-5px;">CASE</span></a></li>
                    <li class="nav-item nav-link doc-nav" style="width:170px; text-align:center"><a @*href="@Url.Action("Choice","Notification")"*@ id="close" class="btn btn-lg btn-module doc-type" role="button"><span class="glyphicon-lg glyphicon glyphicon-erase"></span> <br /><span style="font-size:10px; font-weight:bold; margin-left:-5px;">CLOSED</span></a></li>
                </ul>
            </div>
        </div><br /><br /><br /><br /><br /><br />
        <!-- jQuery and Bootstrap's JavaScript-->
        <div id="contentDiv">

        </div>

    </div>

</div>

<script>
    $(document).ready(function () {
        var url = '@Url.Action(page, Model.Module)';
        $("#contentDiv").load(url);
    });

    $(function () {
        @*$('#dashboard').click(function () {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_Index", "Case")';
            $("#contentDiv").load(url);
            $('#dashboard').parent().addClass('active');
            $('#lead').parent().removeClass('active');
            $('#appointment').parent().removeClass('active');
            $('#case').parent().removeClass('active');
        });*@
        $('#lead').click(function () {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_Index", "Lead")';
            $("#contentDiv").load(url);
        });
        $('#appointment').click(function() {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_Index", "Appointment")';
            $("#contentDiv").load(url);
        });
        $('#case').click(function() {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_CaseIndex", "Case")';
            $("#contentDiv").load(url);
        });
        
        $('#close').click(function() {
            $('#contentDiv').children().remove();
            var url = '@Url.Action("_Index", "Close")';
            $("#contentDiv").load(url);
        });
    });
</script>